### PR TITLE
Update tsibble to 0.8.2

### PR DESCRIPTION
**Pull request by philip-khor**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
@philip-khor Why did you 'Revert changes to compilers'?... those are intentional ... toolchain is deprecated as the linter is telling. The conda-build cran skeleton was recently updated accordingly.

**Comment by philip-khor** [comment]
@dbast the Windows check failed. Also looks like conda smithy rerender didn't come through ... will revert, sorry!

**Comment by dpryan79** [comment]
Why not just fix that and bump the build number?

**Comment by dbast** [comment]
@philip-khor: If you want to fully update a feedstock locally via recreation+rerender, you need to update `conda-build, `conda-smithy` and `conda_r_skeleton_helper` to the latest versions. And always rerender after updating the meta.yaml or let conda-forge-admin rerender for you after opening the PR.

**Comment by philip-khor** [comment]
Bumped the build number and rerendered (#6)

**Pull request merged**
